FROM        scratch

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7-1768783948

LABEL name="Test project 2"
LABEL description="Konflux Test project 2"
LABEL io.k8s.description="Konflux Test project 2"
LABEL io.k8s.display-name="Test-project 2"
LABEL summary="Konflux Test project 2"
LABEL io.openshift.tags="konflux"

ENTRYPOINT ["/bin/bash"]